import type { NextPage } from "next";
import Head from "next/head";
import React, { useEffect, useRef, useState } from "react";
import BgVideo from "../components/BgVideo";
import Header from "../components/header";
import { motion, useInView } from "framer-motion";

const Home: NextPage = () => {
  const [opacity, setOpacity] = useState<number>(0);
  const [blur, setBlur] = useState<boolean>(false);

  useEffect(() => {
    const onScroll = () => {
      if (window.scrollY <= window.screen.height / 2) {
        setOpacity(0);
        setBlur(false);
      }

      // 一画面分スクロールした時の動き
      if (window.scrollY > window.screen.height / 2) {
        setOpacity(50);
        setBlur(true);
        console.log(blur);
      }
    };

    window.addEventListener("scroll", () => onScroll());

    return () => window.removeEventListener("scroll", () => onScroll());
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen">
        <Header opacity={opacity} />
        <BgVideo blur={blur} />

        <div
          id="top-bg-video-spacer"
          className={`
          w-screen h-screen bg-tranceparent ease-in duration-100
          font-bold text-5xl text-gray-900
          flex items-center justify-center
        `}
        >
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.5 }}
          >
            <h1>This is TOP Content.</h1>
          </motion.div>
        </div>

        <div className="w-full h-full p-10">
          <motion.div
            initial={{ opacity: 0, width: 0, x: 10 }}
            whileInView={{ opacity: 1, width: "100%", x: 0 }}
            transition={{ duration: 1, origin: 1 }}
            //whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, amount: 0.5 }}
          >
            <div className="bg-white bg-opacity-10 rounded p-5">
              <h1 className="text-xl font-bold">About this site.</h1>
              <div>framer-motion-work is my etude</div>
            </div>

            <div className="p-3"></div>

            <div className="bg-white bg-opacity-10 rounded p-5">
              <h1 className="text-xl font-bold">About this member.</h1>
              <div>framer-motion-work is my etude</div>
            </div>
          </motion.div>
        </div>

        <div
          id="bottom-spacer"
          className={`w-screen h-screen bg-tranceparent ease-in duration-100
        `}
        ></div>
      </main>
    </>
  );
};

export default Home;
