import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import BgVideo from "../components/bg_video";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <BgVideo />

      <div className="w-full h-fill z-10 bg-indigo-50">aaa</div>
    </>
  );
};

export default Home;
